### ISSUE TITLE
Publish 1.3.2 on www.npmjs.com ?

### ISSUE THREAD

**Issue by ericjamesbye7** [nextcloud-libraries/nextcloud-moment#959]
Hello
Is it possible to publish the 1.3.2 on https://www.npmjs.com/ ?
Thx
Regards
EJB

**Comment by dartcafe** [comment]
@susnux Any reason, this release is not available from npmjs.com?

**Comment by susnux** [comment]
Was just forgotten.  Released now

**Comment by ericjamesbye7** [comment]
And thank you :o)
have a good day
